export const indicesOptions = [
    { label: "ALL INDICES", value: "1" },
    { label: "NIFTY 50", value: "1" },
    { label: "SENSEX", value: "2" },
    { label: "NIFTY BANK", value: "1" },
    { label: "NIFTY 500", value: "1" },
    { label: "NIFTY MIDCAP 100", value: "1" },
    { label: "NIFTY SMLCAP 250", value: "1" },
    { label: "NIFTY AUTO", value: "1" },
    { label: "INDIA VIX", value: "1" },
    { label: "NIFTY CONSR DURBL", value: "1" },
    { label: "NIFTY CPSE", value: "1" },
    { label: "NIFTY ENERGY", value: "1" },
    { label: "NIFTY FIN SERVICE", value: "1" },
    { label: "NIFTY FMCG", value: "1" },
    { label: "NIFTY HEALTHCARE", value: "1" },
    { label: "NIFTY IND DIGITAL", value: "1" },
    { label: "NIFTY INFRA", value: "1" },
    { label: "NIFTY IT", value: "1" },
    { label: "NIFTY MEDIA", value: "1" },
    { label: "NIFTY METAL", value: "1" },
    { label: "NIFTY OIL AND GAS", value: "1" },
    { label: "NIFTY PHARMA", value: "1" },
    { label: "NIFTY MNC", value: "1" },
    { label: "NIFTY PSU BANK", value: "1" },
    { label: "NIFTY PVT BANK", value: "1" },
    { label: "NIFTY REALTY", value: "1" },
    { label: "NIFTY NEXT 50", value: "1" },
    { label: "NIFTY 100", value: "1" },
    { label: "NIFTY 200", value: "1" },
    { label: "NIFTY COMMODITIES", value: "1" },
    { label: "NIFTY MID SELECT", value: "1" },
    { label: "NIFTY IND DEFENCE", value: "1" },
    { label: "NIFTY RURAL", value: "1" },
    { label: "NIFTY CONSUMPTION", value: "1" },

];
